server:
  port: 8082

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3307/spring_aio
    username: root
    password: "07310731"
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
  profiles:
    active: dev

